### PR TITLE
14 update getstate to return an array which could be extracted like react usestate

### PR DESCRIPTION
**Pull request by rabisnaqvi**
- Updated the getState function to return an array similiar to how useState hook works
- Minor adjustment, instead of passing setState we are now passing a lister function instead.
- Updated unit tests to match the updated response from Astral.context.getState.

### CODE REVIEW

**Comment by rabisnaqvi** [comment]
@Siar416 thanks for contributing to this project! really appreciated. I have merged the changes after updating the unit tests etc ✨
It'd be great if you could star the project! means a lot to me :))

**Comment by Siar416** [comment]
Just to confirm, I could go ahead and change the variable that is "var" to
"let" and "const"? Those changes would then be merged into an internal
feature branch instead of release-candidate

**Comment by rabisnaqvi** [comment]
Yup, that is correct! I have created an internal branch (15-integrate-typescript-or-babel), when you want, you can create a pull request to this internal branch rather than release-candidate.

**Comment by Siar416** [comment]
Awesome! I'll start working on that once I get a chance. Either later today
or tomorrow.

**Pull request merged**
